Backport pipeline improvements for EL7/8/Microos
rancher/rancher-selinux pull request #27
Opened 2023-10-27 21:52 UTC by andypitcher

2023-10-30 17:36 UTC, macedogm requested changes
Can you please also remove the following Docker volume lines that were only needed when using Dapper's Docker-in-Docker build?

**Part 1**
https://github.com/rancher/rancher-selinux/blob/e449419dc13e6fc66d6db8dd1f36a744d77bda15/.drone.yml#L14-L16

**Part 2**
https://github.com/rancher/rancher-selinux/blob/e449419dc13e6fc66d6db8dd1f36a744d77bda15/.drone.yml#L95-L98

2023-10-30 17:36 UTC, macedogm commented on policy/centos7/scripts/build
> +yum install -y container-selinux selinux-policy-devel yum-utils rpm-build # git
```suggestion
yum install -y container-selinux selinux-policy-devel yum-utils rpm-build
```

2023-10-30 17:36 UTC, macedogm commented on policy/centos7/scripts/upload-repo
> +unzip awscliv2.zip
```suggestion
unzip -q awscliv2.zip
```

2023-10-30 17:36 UTC, macedogm commented on policy/centos7/scripts/upload-repo
> +unzip awscliv2.zip
To make the unzip output quite and remove noise from the CI logs.

2023-10-31 11:39 UTC, macedogm requested changes
Some further changes (that I can't directly point in the PR):

1. In:
https://github.com/rancher/rancher-selinux/blob/686bc8593b812f06b53d1c4cec2cefb6dbe8c7c1/.drone.yml#L167

Need to match the same change done for EL7 -> `- "policy/centos8/dist/**/*.rpm"`

2. In:
https://github.com/rancher/rancher-selinux/blob/686bc8593b812f06b53d1c4cec2cefb6dbe8c7c1/.drone.yml#L353

Need to match the same change done for EL7 -> `- "policy/microos/dist/**/*.rpm"`

2023-10-31 15:08 UTC, andypitcher commented
@macedogm last [commit](https://github.com/rancher/rancher-selinux/pull/27/commits/9b76fbf5d020a4bf5d9fe756fb0adb259835abba) implements your last [recommendation](https://github.com/rancher/rancher-selinux/pull/27#pullrequestreview-1706086357)..

2023-10-31 15:30 UTC, macedogm approved these changes

2023-10-31 15:35 UTC, merged