32 watch permissions are required by fluentbit
rancher/rancher-selinux pull request #33
Opened 2023-11-07 10:54 UTC by lopf

fixes #32

2023-12-01 16:47 UTC, andypitcher requested changes
@lopf could you also include this change in Centos8/rancher.te ? Thanks.

2023-12-04 21:34 UTC, andypitcher approved these changes, later dismissed

2023-12-04 22:20 UTC, andypitcher commented
> CentOS 8 does not have the _watch_ permission available, hence the build fails.

I added the watch permission in the class file, for both centos8 and centos9.

2023-12-05 15:45 UTC, andypitcher approved these changes
@lopf the final commit I made adds the right permissions to the `class:file` in order to append the rules with `watch`.

2023-12-05 18:07 UTC, macedogm approved these changes

2023-12-07 17:13 UTC, merged